### ISSUE TITLE
Webview feature, design update roadmap proposal

### ISSUE THREAD

**Issue by MajorLift** [hb1998/react-component-tree#17]
## Features
- [ ] For opening files, adopt behavior that's consistent with the VSCode file explorer: change current tab file on click, and only open new tab on double/middle click. (Spawning a new tab for every click on a component that's not already open makes it difficult to browse the tree freely.)
- [ ] Make entire tree searchable, not just the currently visible nodes. 
- [ ] Handle duplicate nodes by highlighting all when one is selected (don't expand hidden nodes -- user can use expand all if identifying all duplicate nodes is ther intention). The clicked node should have higher opacity or otherwise be emphasized.

## Webview Design
- [ ] Bold file nodes to distinguish from react router and third party nodes. 
- [ ] Consolidate Expand/Collapse icons into one button with two states.
- [ ] Don't show props icon for components with no props. 
- [ ] Move props icon and redux store icon to right of node name for consistent indenting.
- [ ] Replace "Navigates to that file" tooltip with some info specific to hovered node. 

## Keyboard Navigation 
- [ ] Global hotkey for switching focus to extension (and back to active tab?).
- [ ] PageUp/PageDown support.
- [ ] Skipping through subtrees with Ctrl/Cmd + arrow
- [ ] To top/bottom with Home/End.

These ideas are intended as a starting point for discussion. Any feedback, suggestions, criticism is welcome.

**Comment by hb1998** [comment]
I'd like to add a few things, 
- if its typescript show props with types 
- navigate to that prop (open that file and scroll to it) when clicked on it

**Comment by MajorLift** [comment]
> > Make entire tree searchable, not just the currently visible nodes.
> 
> this is the default search behaviour of vscode.

That's true for the file explorer, but I think the use case of this extension is a bit different. For file explorer, the search tab provides project-wide search functionality, and the explorer tab's search feature is only intended as a supplement. This isn't the case with this extension. The user will expect to have access to a birds-eye view of the entire project, especially if they're interacting with a full-width search bar. Not to mention requiring users to repeatedly click on individual nodes to set up a particular tree state as the search space hurts usability, especially for larger trees. 

We could always add the file explorer's small search popup triggered by `ctrl/cmd + F` for filtering visible nodes as well. But providing the capability to search the full tree at any time should take priority imo. 

Also, I'll add highlighting search matches to the list. Showing the ancestors of matches is a great approach, but with larger trees it becomes very difficult to tell which nodes are search matches and which are there to provide context.

**Comment by MajorLift** [comment]
@hb1998 Granted, I don't think making this change is a huge priority at the moment, especially since the user can always expand-all before searching. 

However, that would mean losing the tree expand state they had previously set up, and it could be very tedious to restore it with manual clicks. Maybe an expand-all/undo toggle button might be a solution, or potentially being able to store and retrieve snapshots of expand state? 

Just brainstorming here. :) I'd love to hear your thoughts.

**Comment by hb1998** [comment]
@MajorLift  we have to somehow figure out a way, without complicating the experience. 
there was another mode in vscode explorer where in you can see the filter results in a separate popup and clicking on it will scroll to that node.

**Comment by MajorLift** [comment]
> @MajorLift we have to somehow figure out a way, without complicating the experience. 

Very much agreed!

> another mode in vscode explorer where in you can see the filter results in a separate popup and clicking on it will scroll to that node.

Could you share how to access this feature? Unless you're talking about the search tab (`Shift + Ctrl/Cmd + F`), I don't think I'm familiar with it.
