### ISSUE TITLE
Parser, Tree class roadmap

### ISSUE THREAD

**Issue by MajorLift** [hb1998/react-component-tree#18]
## Parser

- [ ] Expand import and export statement support.
  - [ ] For static import statements with namespace or default specifiers, add all imported react components to tree. 
  ```ts
  import foo from "mod.js"
  import * as foo from "mod.js"
  ```
  - [ ] For require statements:
    - [ ] Support namespaces and member expressions
    ```ts
    const foo = require("./module"); ... ; <foo.component />;
    ```
    - [ ] Support invocations and method/member calls
    ```ts
    const foo = require("./module")();
    const foo = require("./module").method(arg);
    ```
    - [ ] Add tests for default specifier
    ```ts
    const foo = require("module");
    ```
  - [ ] For dynamic imports:
    - [ ] Add tests for default specifier
    ```ts
    const foo = import("module");
    ```
    - [ ] Support `AwaitExpression`
    ```ts
    const foo = await import("./module")
    ```
    - [ ] Support `Promise.resolve()`
    ```ts
    const foo = Promise.resolve(import("./module"))
    ```
    - [ ] Support `.then()` chains.
    ```ts
    import("./module").then(mod => mod.loadPage())
    ```
    - [ ] Add tests for module imports for side effects only (no values imported)
    ```ts
    import '/modules/my-module.js';
    import 'http:example.com\pears.js';
    ```
    - [ ] Refactor parsing logic for nested Import `CallExpression` in `ArrowFunctionExpression` body to use Babel type guards.
    ```ts
    const foo = React.lazy(() => import('./module'));
    ```
  - [ ] Add support for barrel files. 
    - 1) Recognize barrel files
    - 2) Parse export statements in barrel file
    - 3) Parse export statements for components in individual modules.

- [ ] Rewrite `.getJSXChildren()`, `.getJSXProps()`, `.checkForRedux()` methods to use Babel type guards.
  - [ ] Add support for Redux hooks.
     - https://github.com/oslabs-beta/sapling/issues/107

- [ ] Add support for file paths containing `.`
  - https://github.com/oslabs-beta/sapling/issues/108
 
---

## Tree

- [ ] Consolidate Tree and Node data class/interfaces for parser, serialized workspace cache, and webview.
  - Each require a slightly different set of properties.
